### ISSUE TITLE
Window buttons are not visible

### ISSUE THREAD

**Issue by AlexJakeGreen** [soreau/pixdecor#12]
Current implementation expects a specific [set of files](https://github.com/soreau/pixdecor/blob/master/src/deco-theme.cpp#L251) to be installed, which can be absent in several distributions.

Observed: Black squares instead of maximize, minimize and close buttons

**Comment by soreau** [comment]
Yes, this is a known problem. I think we should draw buttons with cairo if any of the buttons are not found.

**Comment by DivineToast** [comment]
Hello! I appear to be one of the people missing the specific files, getting the same black squares instead of the buttons. Is there a workaround for this in the meantime while waiting for a proper fix? If it is as easy as obtaining the missing files then a polite pointing in the right direction would be greatly appreciated!

**Comment by soreau** [comment]
[This code](https://github.com/soreau/pixdecor/blob/master/src/deco-theme.cpp#L193) would need to be modified. One option is to draw the buttons with cairo, so it doesn't rely on certain system package files and settings.

**Comment by soreau** [comment]
This should now work in latest pixdecor since [this commit](https://github.com/soreau/pixdecor/commit/ea7aa60fc5fd7744bae4a0f9e0d3afd9246d6eeb).
